name: Grafana Packer Image CI Build

on:
  push:
    branches: [ main ]
    paths: 
    - 'grafana/v9.5.3/**'

env:
  PRODUCT_VERSION: "v1.6.6" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to docker hub
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PWD
      
      - name: Prepare image tag
        run: echo "TAG=$(date +'%F-%H-%M-%S')" >> $GITHUB_ENV  

      - name: Setup `packer`
        uses: nomuken/setup-packer@v1
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init grafana/v9.5.3/grafana.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate grafana/v9.5.3/grafana.pkr.hcl"
      
      - name: Run `packer build`
        id: build
        run: "packer build grafana/v9.5.3/grafana.pkr.hcl"
        
      - name: Tag and Push the packer image to dockerhub
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
        run: |
          docker tag coredge/grafana:v9.5.3-0 rishabh0197/grafana:${{ env.TAG }}
          docker tag coredge/grafana:v9.5.3-0 rishabh0197/grafana:latest

          docker push coredge/grafana:v9.5.3-0 rishabh0197/grafana:${{ env.TAG }}
          docker push coredge/grafana:v9.5.3-0 rishabh0197/grafana:latest
