name: Grafana Packer Image CI Build

on:
  push:
    branches: [ main ]
    paths: 
    - 'grafana/v9.5.3/**'

env:
  PRODUCT_VERSION: "v1.6.6" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to docker hub
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PWD
      
      - name: Prepare image tag
        run: echo "TAG=$(date +'%F-%H-%M-%S')" >> $GITHUB_ENV  

      - name: Setup `packer`
        uses: nomuken/setup-packer@v1
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      
      - name: Configure AWS credentials
        run: |
          cd grafana/v9.5.3/ && touch credentials
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> credentials
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> credentials

      - name: Create AWS configuration file
        run: |
          cd grafana/v9.5.3/ && touch config
          echo "[default]" >> config
          echo "region = ap-south-1" >> config
          echo "output = table" >> config

      - name: Run `packer init`
        id: init
        run: "cd grafana/v9.5.3/ && packer init grafana.pkr.hcl"
      
#       - name: Configure AWS credentials from Test account
#         uses: aws-actions/configure-aws-credentials@v2
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: 'ap-south-1'
      
      - name: Run `packer validate`
        id: validate
        run: "cd grafana/v9.5.3/ && packer validate grafana.pkr.hcl"
      
      - name: Run `packer build`
        id: build
        run: "cd grafana/v9.5.3/ && packer build grafana.pkr.hcl"
        
      - name: Tag and Push the packer image to dockerhub
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
        run: |
          docker tag coredge/baseos-beta:v9.5.3-0 rishabh0197/grafana:${{ env.TAG }}
          docker tag coredge/baseos-beta:v9.5.3-0 rishabh0197/grafana:latest

          docker push rishabh0197/grafana:${{ env.TAG }}
          docker push rishabh0197/grafana:latest
